#!/bin/sh
NUM=0
ARGS=()
for var in "$@"
do 
    if [[ $var =~ ^--num=(.*) ]]
    then
        NUM=${BASH_REMATCH[1]}
    else 
        ARGS+=($var)
    fi
    echo "$var"
done
export KUBECONFIG=~/.kube/custom-test-${CLUSTER_NUM}
oc login "$ARGS"
exec /bin/bash
